import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  zones: [
    {
      zone: 'Alto Quebradilla',
      district: 'quebradilla',
      price: 100,
    },
    {
      zone: 'Centro Quebradilla',
      district: 'quebradilla',
      price: 100,
    },
    {
      zone: 'La rueda Quebradilla',
      district: 'quebradilla',
      price: 100,
    },
    {
      zone: 'Condominios Quebradilla',
      district: 'quebradilla',
      price: 100,
    },
    {
      zone: 'Colegio Quebradilla',
      district: 'quebradilla',
      price: 100,
    },
    {
      zone: 'Papera Tablon',
      district: 'tablon',
      price: 100,
    },
    {
      zone: 'La plaza Tablon',
      district: 'tablon',
      price: 100,
    },
    {
      zone: 'Iglesia Tobosi',
      district: 'tobosi',
      price: 100,
    },
    {
      zone: 'Entrada Tobosi-Quebradilla',
      district: 'tobosi',
      price: 100,
    },
    {
      zone: 'Entrada Tobosi-Barrancas',
      district: 'tobosi',
      price: 100,
    },
    {
      zone: 'Barrio la cruz',
      district: 'tobosi',
      price: 100,
    },
  ],
  products: [
    {
      name: '4 piezas de pollo',
      slug: 'promocion-4-piezas',
      category: 'papas',
      image: '/images/promociones.jpg',
      isFeatured: false,
      featuredImage: '',
      price: 70,
      description: 'Promocion de pollo',
      isPromotion: true,
      isCombo: false,
      isAvailable: true,
    },
    {
      name: '6 piezas de pollo',
      slug: 'promocion-6-piezas',
      category: 'papas',
      image: '/images/promociones.jpg',
      isFeatured: false,
      featuredImage: '',
      price: 100,
      description: 'Promocion de pollo',
      isPromotion: true,
      isCombo: false,
      isAvailable: true,
    },
    {
      name: '8 piezas de pollo',
      slug: 'promocion-8-piezas',
      category: 'papas',
      image: '/images/promociones.jpg',
      isFeatured: false,
      featuredImage: '',
      price: 130,
      description: 'Promocion de pollo',
      isPromotion: true,
      isCombo: false,
      isAvailable: true,
    },
    {
      name: '10 piezas de pollo',
      slug: 'promocion-10-piezas',
      category: 'pollo',
      image: '/images/promociones.jpg',
      isFeatured: false,
      featuredImage: '',
      price: 150,
      description: 'Promocion de pollo',
      isPromotion: true,
      isCombo: false,
      isAvailable: true,
    },
    {
      name: 'banners 1',
      slug: 'banners-1',
      category: 'pollo',
      image: '/images/banner1.jpg',
      isFeatured: true,
      featuredImage: '/images/banner1.jpg',
      price: 200,
      description: 'Promocion de pollo',
      isPromotion: false,
      isCombo: false,
      isAvailable: true,
    },
    {
      name: 'banners 2',
      slug: 'banners-2',
      category: 'pollo',
      image: '/images/banner2.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 200,
      description: 'Promocion de pollo',
      isPromotion: false,
      isCombo: false,
      isAvailable: true,
    },
  ],
  categories: [
    {
      name: 'Pollo',
      identifier: 'pollo',
      image: '/images/categoriaPollo.jpg',
    },
    {
      name: 'Papas',
      identifier: 'papas',
      image: '/images/categoriaPapas.jpg',
    },
  ],
};
export default data;
